#!/bin/bash
START=`date +%s%N`
awk '{print $1}' /var/log/apache2/access.log | sort | uniq -c | wc -l > /dev/null 2>&1
MIDDLE=`date +%s%N`
cat /var/log/apache2/access.log | awk '{print $1}' | sort | uniq -c | wc -l > /dev/null 2>&1
END=`date +%s%N`
FIRST=$(($MIDDLE-$START))
SECOND=$(($END-$MIDDLE))
echo "First: $FIRST"
echo "Second: $SECOND"
