#!/usr/bin/expect -f

set keyfile "/etc/apache2/ssl/wantlistapp-star.key"
set certfile "/etc/apache2/ssl/wantlistapp-star.crt"

spawn openssl req -new -newkey rsa:2048 -nodes -keyout $keyfile -out $certfile

expect "Country"
send -- "US\r"

expect "State"
send -- "California\r"

expect "Locality"
send -- "San Francisco\r"

expect "Organization Name"
send -- "Wantlist\r"

expect "Organizational Unit"
send -- "\r"

expect "Common Name"
send -- "*.wantlistapp.com\r"

expect "Email Address"
send -- "jason.chavannes@gmail.com\r"

expect "password"
send -- "\r"

expect "company"
send -- "\r"

expect eof

