#!/bin/bash

LC_NUMERIC="en_US.UTF-8"
LOG_FILE="datacheck.log"

# Use input as threshold or default to 50 MiB
if [[ $1 =~ ^[0-9]+$ ]] && [ $1 -gt 0 ]; then
  THRESHOLD=$1
else
  THRESHOLD=50
fi

# Data is accurate to two decimal places, but it's
# easier to work in integers
THRESHOLD=$(($THRESHOLD*100))

# Count how many times notification has been triggered
PREV=`test -f $LOG_FILE && cat $LOG_FILE | grep "$(date +%D)" | awk '{print $1}' | uniq -c | awk '{print $1}'`
UNITS=`test -f $LOG_FILE && tail -n 1 $LOG_FILE | awk '{print $5}' | cut -c1-3`

# If notification has been triggered, multiply threshold
if [[ $PREV =~ ^[0-9]+$ ]] && [ $PREV -gt 0 ]; then
  THRESHOLD=$(($THRESHOLD*($PREV+1)))
fi

# Get current daily usage
set `vnstat -d | grep "$(date +%D)" | awk '{print $8*100,$9,$8}'`

echo "$3 $2"


if [ "$2" = "GiB" ]; then
  CURRENT=$(($1*1000))
else
  CURRENT=$1
fi

# If usage over threshold, send email and log
if [ $CURRENT -gt $THRESHOLD -a "$2" != "KiB" ]; then
  THRESHOLD=$(($THRESHOLD/100))
  DATE=`date +%D`
  TIME=`date +%r`
  if [ $THRESHOLD -gt 999 ]; then
    THRESHOLD=`echo "scale=2;$THRESHOLD/1000" | bc`
  else
    UNITS="MiB"
  fi
  echo "Subject: Daily bandwidth usage - $DATE
From: notifications@jchavannes.com
To: jason.chavannes@gmail.com
Bandwidth usage currently at $3 $2 (Threshold is $THRESHOLD $UNITS).

Generated on $DATE at $TIME.
  " | sendmail "jason.chavannes@gmail.com"
  echo "$DATE, $TIME, $3 $2, $THRESHOLD $UNITS" >> $LOG_FILE
  echo "Mail sent!"
else
  echo "No alert."
fi

