#!/bin/bash

LC_NUMERIC="en_US.UTF-8"

# Use input as threshold or default to 50 MiB
if [[ $1 =~ ^[0-9]+$ ]] && [ $1 -gt 0 ]; then
  THRESHOLD=$1
else
  THRESHOLD=50
fi

# Data is accurate to two decimal places, but it's
# easier to work in integers
THRESHOLD=$(($THRESHOLD*100))

# Count how many times notification has been triggered
PREV=`test -f log && cat log | grep "$(date +%D)" | awk '{print $1}' | uniq -c | awk '{print $1}'`

# If notification has been triggered, multiply threshold
if [[ $PREV =~ ^[0-9]+$ ]] && [ $PREV -gt 0 ]; then
  THRESHOLD=$(($THRESHOLD*($PREV+1)))
fi

# Get current daily usage
set `vnstat -d | grep "$(date +%D)" | awk '{print $8*100,$9}'`

# If usage over threshold, send email and log
if [ $1 -gt $THRESHOLD -a $2 != "KiB" ] || [ $2 != "KiB" -a $2 != "MiB" ]; then
  AMOUNT=$(($1/100))
  DEC=$(($1-($AMOUNT*100)))
  AMOUNT=`printf "%'.0f.%'2.0f" $AMOUNT $DEC`
  THRESHOLD=$(($THRESHOLD/100))
  DATE=`date +%D`
  TIME=`date +%r`
  echo "Subject: Daily bandwidth usage - $DATE
From: notifications@jchavannes.com
To: jason.chavannes@gmail.com
Bandwidth usage currently at $AMOUNT $2 (Threshold set at $THRESHOLD MiB).

Generated on $DATE at $TIME.
  " | sendmail "jason.chavannes@gmail.com"
  echo "$DATE, $TIME, $AMOUNT $2, $THRESHOLD MiB" >> log
fi

